apiVersion: management.cattle.io/v3
displayName: ReadOnly for rancher-inventory
kind: GlobalRole
metadata:
  generateName: gr-
rules:
  - apiGroups:
      - management.cattle.io
    resources:
      - clusters
    verbs:
      - get
  - apiGroups:
      - management.cattle.io
    resources:
      - settings
    verbs:
      - get
