apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: spacestep-link
spec:
  label: "Spacestep UI"
  description: "OS pathing state"
  toURL: "/k8s/clusters/local/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/"
  group: "Spacestep"
  target: "_blank"
