apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-inventory-client
  namespace: rancher-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-inventory
  template:
    metadata:
      labels:
        app: rancher-inventory
    spec:
      containers:
        - name: watcher
          env:
            - name: RANCHER_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: rancher-api-token
            - name: TARGET_URL
              value: https://webhook.site/ef9fb9ab-f11d-4e48-9d1e-e4c331e802e1
            - name: POLL_INTERVAL
              value: '60'
            - name: PYTHONUNBUFFERED
              value: '1'
          image: registry.gitlab.com/davidhrbac/rancher-inventory/client:0.18
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
      restartPolicy: Always

