kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: kured
spec:
  template:
    spec:
      containers:
        - name: kured
          args:
            - '--reboot-sentinel-command=sh -c "! needs-restarting --reboothint"'
